(async()=>{
if(!await ContentPage.init())return;
const $=id=>document.getElementById(id),MAX_LOGO_BYTES=2*1024*1024,ALLOWED_LOGO_TYPES=new Set(["image/png","image/jpeg","image/webp"]);
let items=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function escAttr(v){return esc(v).replace(/"/g,"&quot;")}
function brandVisual(x){const fallback=`<span>${esc(x.brand_abbr||"-")}</span>`;return `<div class="brandBadge brandLogoBox">${x.logo_url?`<img src="${escAttr(x.logo_url)}" alt="โลโก้ ${escAttr(x.brand_name||"")}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${esc(x.brand_abbr||"-")}</span>`:fallback}</div>`}
async function load(){try{const d=await AdminAuth.json("/api/brands");items=d.items||[];render()}catch(e){SwalSmall.error("โหลดรายการแบรนด์ไม่สำเร็จ",e.message)}}
function render(){
 const q=$("brandSearch").value.trim().toLowerCase(),filtered=items.filter(x=>!q||`${x.brand_name||""} ${x.brand_abbr||""} ${x.brand_id||""}`.toLowerCase().includes(q));
 $("brandCount").textContent=`${filtered.length} แบรนด์`;
 $("brandList").innerHTML=filtered.length?filtered.map(x=>`<article class="brandSimpleCard">${brandVisual(x)}<div class="brandSimpleInfo"><strong>${esc(x.brand_name||"-")}</strong><span>ตัวย่อ ${esc(x.brand_abbr||"-")} · ${x.logo_url?"มีโลโก้":"ยังไม่มีโลโก้"}</span></div><div class="brandSimpleState ${x.active?"on":"off"}">${x.active?"ใช้งาน":"ปิดใช้งาน"}</div><div class="brandSimpleActions"><button class="ghost editBtn" data-id="${escAttr(x.brand_id)}">แก้ไข</button><button class="ghost dangerBtn deleteBtn" data-id="${escAttr(x.brand_id)}">ลบ</button></div></article>`).join(""):'<div class="emptyList">ยังไม่มีแบรนด์</div>';
 document.querySelectorAll(".editBtn").forEach(b=>b.onclick=()=>editBrand(b.dataset.id));document.querySelectorAll(".deleteBtn").forEach(b=>b.onclick=()=>deleteBrand(b.dataset.id));
}
function validateLogo(file){if(!file)return "";if(!ALLOWED_LOGO_TYPES.has(file.type))return "รองรับเฉพาะ PNG, JPG และ WebP";if(file.size<=0||file.size>MAX_LOGO_BYTES)return "ไฟล์โลโก้ต้องมีขนาดไม่เกิน 2 MB";return ""}
async function brandDialog(existing=null){
 let previewUrl="";const current=existing?.logo_url?`<img id="swLogoPreview" src="${escAttr(existing.logo_url)}" alt="โลโก้ปัจจุบัน">`:`<div id="swLogoFallback">${esc(existing?.brand_abbr||"LOGO")}</div>`;
 const result=await OfficeSwal.fire({title:existing?"แก้ไขแบรนด์":"เพิ่มแบรนด์",width:520,focusConfirm:false,customClass:{popup:"swal-compact brandEditorModal"},html:`<div class="swalForm brandEditorForm"><div class="brandLogoEditor"><div class="brandLogoPreview">${current}</div><div class="brandLogoControls"><strong>โลโก้แบรนด์</strong><span>PNG, JPG หรือ WebP · ไม่เกิน 2 MB</span><label class="brandLogoChoose">เลือกภาพโลโก้<input id="swBrandLogo" type="file" accept="image/png,image/jpeg,image/webp"></label></div></div>${existing?.logo_url?'<label class="swalCheck brandLogoRemove"><input id="swRemoveLogo" type="checkbox"> ลบโลโก้เดิมและกลับไปใช้ตัวย่อ</label>':""}<label>ชื่อแบรนด์<input id="swBrandName" class="swal2-input" value="${escAttr(existing?.brand_name||"")}" placeholder="เช่น L-go fresh"></label><label>ตัวย่อ<input id="swBrandAbbr" class="swal2-input" maxlength="30" value="${escAttr(existing?.brand_abbr||"")}" placeholder="เช่น LGF"></label><label class="swalCheck"><input id="swBrandActive" type="checkbox" ${existing?.active===0?"":"checked"}> ใช้งานแบรนด์นี้</label></div>`,showCancelButton:true,confirmButtonText:"บันทึก",cancelButtonText:"ยกเลิก",
  didOpen:()=>document.getElementById("swBrandLogo").addEventListener("change",event=>{const file=event.target.files?.[0],error=validateLogo(file);if(error){event.target.value="";Swal.showValidationMessage(error);return}Swal.resetValidationMessage();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);const host=document.querySelector(".brandLogoPreview");host.innerHTML='<img id="swLogoPreview" alt="ตัวอย่างโลโก้">';host.querySelector("img").src=previewUrl;const remove=document.getElementById("swRemoveLogo");if(remove)remove.checked=false}),
  preConfirm:()=>{const brandName=document.getElementById("swBrandName").value.trim(),brandAbbr=document.getElementById("swBrandAbbr").value.trim().toUpperCase(),active=document.getElementById("swBrandActive").checked,logo=document.getElementById("swBrandLogo").files?.[0]||null,removeLogo=Boolean(document.getElementById("swRemoveLogo")?.checked);if(!brandName){Swal.showValidationMessage("กรุณากรอกชื่อแบรนด์");return false}if(!brandAbbr){Swal.showValidationMessage("กรุณากรอกตัวย่อ");return false}const error=validateLogo(logo);if(error){Swal.showValidationMessage(error);return false}return{brandName,brandAbbr,active,logo,removeLogo}},willClose:()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)}});
 return result.isConfirmed?result.value:null;
}
async function uploadLogo(brandId,file){const form=new FormData();form.append("logo",file,file.name);return AdminAuth.json(`/api/brands/${encodeURIComponent(brandId)}/logo`,{method:"POST",body:form})}
async function removeLogo(brandId){return AdminAuth.json(`/api/brands/${encodeURIComponent(brandId)}/logo`,{method:"DELETE"})}
async function saveBrand(brandId,v){await AdminAuth.json("/api/brands",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brandId,brandName:v.brandName,brandAbbr:v.brandAbbr,active:v.active})});if(v.logo)await uploadLogo(brandId,v.logo);else if(v.removeLogo)await removeLogo(brandId)}
async function addBrand(){const v=await brandDialog();if(!v)return;const brandId=v.brandName.trim().toUpperCase().replace(/[^A-Z0-9ก-๙]+/g,"_").replace(/^_+|_+$/g,"");if(!brandId){SwalSmall.error("เพิ่มแบรนด์ไม่สำเร็จ","ไม่สามารถสร้างรหัสแบรนด์จากชื่อที่ระบุ");return}try{await saveBrand(brandId,v);await SwalSmall.ok("เพิ่มแบรนด์แล้ว",v.logo?"บันทึกข้อมูลและโลโก้ใน R2 แล้ว":`${v.brandName} • ${v.brandAbbr}`);await load()}catch(e){SwalSmall.error("เพิ่มแบรนด์ไม่สำเร็จ",e.message)}}
async function editBrand(id){const x=items.find(i=>i.brand_id===id);if(!x)return;const v=await brandDialog(x);if(!v)return;try{await saveBrand(id,v);await SwalSmall.ok("บันทึกการแก้ไขแล้ว",v.logo?"เปลี่ยนโลโก้ใน R2 แล้ว":v.removeLogo?"ลบโลโก้แล้ว":v.brandName);await load()}catch(e){SwalSmall.error("แก้ไขแบรนด์ไม่สำเร็จ",e.message)}}
async function deleteBrand(id){const x=items.find(i=>i.brand_id===id);if(!x)return;const r=await OfficeSwal.fire({title:"ปิดใช้งานแบรนด์",html:`<div class="officeDialogIntro officeDialogIntro--danger"><span aria-hidden="true">!</span><div><strong>${esc(x.brand_name)}</strong><p>${esc(x.brand_abbr||x.brand_id)} · จะไม่แสดงสำหรับงานใหม่</p></div></div>`,showCancelButton:true,confirmButtonText:"ปิดใช้งาน",cancelButtonText:"ยกเลิก",officeKind:"danger"});if(!r.isConfirmed)return;try{await AdminAuth.json(`/api/brands/${encodeURIComponent(id)}`,{method:"DELETE"});await SwalSmall.ok("ปิดใช้งานแบรนด์แล้ว",x.brand_name);await load()}catch(e){SwalSmall.error("ปิดใช้งานแบรนด์ไม่สำเร็จ",e.message)}}
$("addBrandBtn").onclick=addBrand;$("brandSearch").oninput=render;await load();
})();
