(async()=>{
  if(!await ContentPage.init())return;
  const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const statusText={SUBMITTED:"รอตรวจ",RETURNED:"ส่งกลับแก้ไข",APPROVED:"ผ่านการตรวจ",REJECTED:"ไม่อนุมัติ"};
  let list=[],selectedId=null,images=[],imageIndex=0,zoom=1,rotation=0,panX=0,panY=0,drag=null,objectUrls=[];
  const formatDate=v=>{const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:v||"-"};
  function queueCard(s){return `<button class="reviewQueueItem ${Number(s.id)===Number(selectedId)?"active":""}" data-id="${s.id}"><span class="queueBrand">${esc(s.brand_abbr||s.brand||"-")}</span><span class="queueMain"><strong>${esc(s.store_name||"ไม่ระบุชื่อร้าน")}</strong><small>${esc(s.store_code||"-")} · ${formatDate(s.work_date)}</small><small>${esc(s.full_name||s.employee_name||s.employee_code||"-")}</small></span><span class="statusBadge status-${String(s.status||"").toLowerCase()}">${statusText[s.status]||esc(s.status||"-")}</span></button>`}
  function renderQueue(){const term=$("reviewSearch").value.trim().toLowerCase(),visible=term?list.filter(x=>[x.store_code,x.store_name,x.full_name,x.employee_name,x.employee_code,x.brand].some(v=>String(v||"").toLowerCase().includes(term))):list;$("reviewCount").textContent=visible.length;$("reviewQueue").innerHTML=visible.map(queueCard).join("")||'<div class="officeEmpty">ไม่พบงานตามตัวกรอง</div>';document.querySelectorAll(".reviewQueueItem").forEach(b=>b.onclick=()=>openSubmission(Number(b.dataset.id)))}
  async function load(){try{$("reviewQueue").innerHTML='<div class="officeEmpty">กำลังโหลดข้อมูล</div>';const d=await AdminAuth.json(`/api/admin/submissions?status=${encodeURIComponent($("reviewStatus").value)}`);list=d.items||[];if(selectedId&&!list.some(x=>Number(x.id)===Number(selectedId)))selectedId=null;renderQueue()}catch(e){$("reviewQueue").innerHTML=`<div class="officeError">โหลดคิวตรวจสอบไม่สำเร็จ<br><small>${esc(e.message)}</small></div>`}}
  function scanImages(value,path="",out=[]){if(value==null)return out;if(Array.isArray(value)){value.forEach((v,i)=>scanImages(v,`${path}.${i}`,out));return out}if(typeof value==="object"){Object.entries(value).forEach(([k,v])=>{const p=path?`${path}.${k}`:k;if(typeof v==="string"&&/(image|photo|picture|receipt|bill|store.*url|url.*store)/i.test(p)&&(/^(https?:|data:image|blob:|\/api\/)/i.test(v)))out.push({label:/store/i.test(p)?"ภาพหน้าร้าน":/receipt|bill/i.test(p)?"ภาพบิล":"ภาพหลักฐาน",src:v});else if(typeof v==="object")scanImages(v,p,out)});return out}return out}
  async function prepareImages(raw){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];const found=scanImages(raw),seen=new Set();images=[];for(const x of found){if(seen.has(x.src))continue;seen.add(x.src);if(x.src.startsWith("/api/")){try{const r=await AdminAuth.request(x.src);if(r.ok){const u=URL.createObjectURL(await r.blob());objectUrls.push(u);images.push({...x,src:u})}}catch{}}else images.push(x)}imageIndex=0;resetView()}
  function imageStrip(){return images.length?`<div class="evidenceTabs">${images.map((x,i)=>`<button data-image="${i}" class="${i===imageIndex?"active":""}">${esc(x.label)} ${i+1}</button>`).join("")}</div>`:'<div class="evidenceMissing"><strong>ยังไม่พบ URL ภาพในข้อมูลที่ API ส่งมา</strong><span>หน้าจอตรวจพร้อมใช้งานทันทีเมื่อ API ส่ง URL ภาพบิลและภาพร้าน</span></div>'}
  function recordTable(rows){return `<div class="recordTableWrap"><table class="officeTable"><thead><tr><th>POS</th><th>ยอดลูกค้า</th><th>วันที่ในบิล</th><th>เวลา</th><th>ผลตรวจ</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><strong>${esc(r.pos_number??i+1)}</strong></td><td class="numberCell">${esc(r.customer_no??r.customer_value??"-")}</td><td>${esc(r.bill_date||"-")}</td><td>${esc(r.bill_time||"-")}</td><td><span class="statusBadge status-approved">พร้อมตรวจ</span></td></tr>`).join("")||'<tr><td colspan="5" class="tableEmpty">ไม่พบข้อมูล POS</td></tr>'}</tbody></table></div>`}
  async function openSubmission(id){selectedId=id;renderQueue();$("reviewDetail").innerHTML='<div class="reviewWelcome"><strong>กำลังเปิดหลักฐาน</strong></div>';try{const d=await AdminAuth.json(`/api/admin/submissions/${id}`),s=d.submission||{},rows=d.records||[];await prepareImages(d);const canReview=s.status==="SUBMITTED";$("reviewDetail").innerHTML=`<header class="reviewDetailHead"><div><div class="detailBreadcrumb">${esc(s.brand||"-")} · ${esc(s.store_code||"-")}</div><h2>${esc(s.store_name||"ไม่ระบุชื่อร้าน")}</h2><p>${formatDate(s.work_date)} · ${esc(s.full_name||s.employee_name||s.employee_code||"-")} · ${rows.length} POS</p></div><span class="statusBadge status-${String(s.status||"").toLowerCase()}">${statusText[s.status]||esc(s.status||"-")}</span></header><div class="reviewSplit"><section class="evidencePanel"><div class="evidenceToolbar"><button data-tool="out" title="ซูมออก">−</button><span id="zoomLabel">100%</span><button data-tool="in" title="ซูมเข้า">＋</button><button data-tool="left" title="หมุนซ้าย">↶</button><button data-tool="right" title="หมุนขวา">↷</button><button data-tool="reset" title="พอดีหน้าจอ">พอดี</button><button data-tool="full" title="เต็มหน้าจอ">เต็มจอ</button></div><div class="evidenceStage" id="evidenceStage">${images.length?'<img id="evidenceImage" alt="ภาพหลักฐาน">':'<div class="imagePlaceholder">ไม่มีภาพสำหรับแสดง</div>'}</div>${imageStrip()}</section><section class="submissionPanel"><div class="submissionFacts"><div><span>รหัสร้าน</span><strong>${esc(s.store_code||"-")}</strong></div><div><span>แบรนด์</span><strong>${esc(s.brand||"-")}</strong></div><div><span>วันที่ทำงาน</span><strong>${formatDate(s.work_date)}</strong></div><div><span>ผู้ปฏิบัติงาน</span><strong>${esc(s.full_name||s.employee_name||s.employee_code||"-")}</strong></div></div><div class="sectionTitle"><strong>ข้อมูลที่อ่านและส่งมา</strong><span>ตรวจเทียบกับภาพบิลก่อนอนุมัติ</span></div>${recordTable(rows)}<label class="reviewNote">หมายเหตุการตรวจ<textarea id="reviewNote" rows="3" placeholder="ระบุหมายเหตุ หรือสิ่งที่ต้องแก้ไข"></textarea></label><div class="reviewActions">${canReview?'<button id="returnSubmission" class="dangerOutline">ส่งกลับแก้ไข</button><button id="approveSubmission" class="primary">ผ่านการตรวจ</button>':'<div class="lockedReview">รายการนี้ดำเนินการแล้ว</div>'}</div></section></div>`;bindDetail(d)}catch(e){$("reviewDetail").innerHTML=`<div class="officeError">เปิดรายละเอียดไม่สำเร็จ<br><small>${esc(e.message)}</small></div>`}}
  function resetView(){zoom=1;rotation=0;panX=0;panY=0}
  function updateImage(){const img=$("evidenceImage");if(!img||!images.length)return;img.src=images[imageIndex].src;img.style.transform=`translate(${panX}px,${panY}px) scale(${zoom}) rotate(${rotation}deg)`;const z=$("zoomLabel");if(z)z.textContent=`${Math.round(zoom*100)}%`;document.querySelectorAll("[data-image]").forEach(b=>b.classList.toggle("active",Number(b.dataset.image)===imageIndex))}
  function bindDetail(raw){updateImage();document.querySelectorAll("[data-image]").forEach(b=>b.onclick=()=>{imageIndex=Number(b.dataset.image);resetView();updateImage()});document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{const t=b.dataset.tool;if(t==="in")zoom=Math.min(4,zoom+.25);if(t==="out")zoom=Math.max(.5,zoom-.25);if(t==="left")rotation-=90;if(t==="right")rotation+=90;if(t==="reset")resetView();if(t==="full")$("evidenceStage").requestFullscreen?.();updateImage()});const stage=$("evidenceStage");if(stage){stage.onwheel=e=>{e.preventDefault();zoom=Math.max(.5,Math.min(4,zoom+(e.deltaY<0?.15:-.15)));updateImage()};stage.onpointerdown=e=>{drag={x:e.clientX-panX,y:e.clientY-panY};stage.setPointerCapture(e.pointerId)};stage.onpointermove=e=>{if(!drag)return;panX=e.clientX-drag.x;panY=e.clientY-drag.y;updateImage()};stage.onpointerup=()=>drag=null}const approve=$("approveSubmission"),back=$("returnSubmission");if(approve)approve.onclick=()=>reviewAction("APPROVE");if(back)back.onclick=()=>reviewAction("RETURN")}
  async function reviewAction(action){const note=$("reviewNote")?.value.trim()||"";if(action==="RETURN"&&!note)return SwalSmall.error("กรุณาระบุสิ่งที่ต้องแก้ไข");const ask=await SwalSmall.confirm(action==="APPROVE"?"ยืนยันว่าข้อมูลถูกต้อง?":"ส่งงานกลับให้แก้ไข?",action==="APPROVE"?"งานจะเปลี่ยนเป็นผ่านการตรวจ":"พนักงานจะเห็นเหตุผลและส่งงานกลับมาใหม่");if(!ask.isConfirmed)return;try{await AdminAuth.json(`/api/admin/submissions/${selectedId}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reason:note})});await SwalSmall.ok(action==="APPROVE"?"ผ่านการตรวจแล้ว":"ส่งกลับแก้ไขแล้ว");selectedId=null;$("reviewDetail").innerHTML='<div class="reviewWelcome"><strong>เลือกรายการถัดไปจากคิว</strong></div>';await load()}catch(e){SwalSmall.error("ดำเนินการไม่สำเร็จ",e.message)}}
  $("reviewStatus").onchange=load;$("refreshReview").onclick=load;$("reviewSearch").oninput=renderQueue;await load();
})();
