(async()=>{
if(!await ContentPage.init())return;
const $=id=>document.getElementById(id);let fieldUsers=[],officeUsers=[],view="FIELD";
const roleNames={FIELD:"ผู้ปฏิบัติงานภาคสนาม",SUPERVISOR:"หัวหน้างาน",DEPARTMENT_HEAD:"หัวหน้าฝ่าย",ADMIN:"ผู้ดูแลระบบ"};
const roleDetails={FIELD:"เข้าใช้งานเฉพาะ APK เพื่อรับแผนงานและส่งข้อมูล",SUPERVISOR:"ภาพรวม ตรวจงาน แผนที่ รายงาน และดูรายการเบิก",DEPARTMENT_HEAD:"ตรวจสอบ รายงาน และอนุมัติเบิกขั้นสุดท้าย",ADMIN:"เข้าใช้งานและจัดการได้ทุกส่วนของระบบ"};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function validPassword(v){v=String(v||"");return v.length>=6&&/\p{L}/u.test(v)&&/\d/.test(v)}
function fmt(v){if(!v)return"ยังไม่มี";const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:v}
async function load(){try{const [f,o]=await Promise.all([AdminAuth.json("/api/users"),AdminAuth.json("/api/admin/staff-users")]);fieldUsers=f.items||[];officeUsers=o.items||[];await Promise.all(fieldUsers.map(async u=>{try{u.plan=await AdminAuth.json(`/api/users/${encodeURIComponent(u.employee_code)}/work-plan-summary`)}catch{u.plan=null}}));render()}catch(e){SwalSmall.error("โหลดรายชื่อไม่สำเร็จ",translate(e.message))}}
function render(){const q=$("userSearch").value.trim().toLowerCase(),list=(view==="FIELD"?fieldUsers:officeUsers).filter(u=>`${u.employee_code||""} ${u.full_name} ${u.username||""}`.toLowerCase().includes(q));$("userCount").textContent=`${list.length} คน`;$("userList").innerHTML=list.map(u=>view==="FIELD"?fieldCard(u):officeCard(u)).join("")||'<div class="emptyList">ยังไม่มีผู้ใช้ในกลุ่มนี้</div>';document.querySelectorAll(".editBtn").forEach(b=>b.onclick=()=>openEditor(b.dataset.kind,b.dataset.id));document.querySelectorAll(".passBtn").forEach(b=>b.onclick=()=>resetPassword(b.dataset.kind,b.dataset.id));document.querySelectorAll(".disableBtn").forEach(b=>b.onclick=()=>disableUser(b.dataset.kind,b.dataset.id));document.querySelectorAll(".deleteUserBtn").forEach(b=>b.onclick=()=>deleteUser(b.dataset.kind,b.dataset.id));document.querySelectorAll(".planBtn").forEach(b=>b.onclick=()=>top.location.href=`admin.html#workplans?user=${encodeURIComponent(b.dataset.id)}`)}
function state(u){return `<div class="brandSimpleState ${u.active?"on":"off"}">${u.active?"ใช้งาน":"ระงับ"}</div>`}
function fieldCard(u){const p=u.plan||{},range=p.firstDate?`${fmt(p.firstDate)} – ${fmt(p.lastDate)}`:"ยังไม่มีแผนงาน";return `<article class="userSimpleCard"><div class="userAvatar">${esc((u.full_name||u.employee_code).slice(0,1))}</div><div class="userMain"><strong>${esc(u.full_name)}</strong><span>รหัส ${esc(u.employee_code)} · ชื่อเข้าระบบ ${esc(u.username||"-")}</span><small class="userRoleText">${roleNames.FIELD}</small></div><div class="userPlan"><strong>${Number(p.itemCount||0)} งาน / ${Number(p.dayCount||0)} วัน</strong><span>${esc(range)}</span></div>${state(u)}<div class="userActions"><button class="ghost planBtn" data-id="${esc(u.employee_code)}">แผนงาน</button><button class="ghost editBtn" data-kind="FIELD" data-id="${esc(u.employee_code)}">แก้ไข</button><button class="ghost passBtn" data-kind="FIELD" data-id="${esc(u.employee_code)}">ตั้งรหัสใหม่</button>${u.active?`<button class="ghost dangerBtn disableBtn" data-kind="FIELD" data-id="${esc(u.employee_code)}">ระงับ</button>`:""}<button class="ghost dangerBtn deleteUserBtn" data-kind="FIELD" data-id="${esc(u.employee_code)}">ลบ</button></div></article>`}
function officeCard(u){return `<article class="userSimpleCard"><div class="userAvatar office">${esc((u.full_name||u.username).slice(0,1))}</div><div class="userMain"><strong>${esc(u.full_name)}</strong><span>ชื่อเข้าระบบ ${esc(u.username)}</span><small class="userRoleText">${esc(roleNames[u.role]||u.role)}</small></div><div class="userPermissionSummary"><strong>${esc(roleNames[u.role]||u.role)}</strong><span>${esc(roleDetails[u.role]||"")}</span></div>${state(u)}<div class="userActions"><button class="ghost editBtn" data-kind="OFFICE" data-id="${u.id}">แก้ไข</button><button class="ghost passBtn" data-kind="OFFICE" data-id="${u.id}">ตั้งรหัสใหม่</button>${u.active?`<button class="ghost dangerBtn disableBtn" data-kind="OFFICE" data-id="${u.id}">ระงับ</button>`:""}<button class="ghost dangerBtn deleteUserBtn" data-kind="OFFICE" data-id="${u.id}">ลบ</button></div></article>`}
function roleCards(selected){return `<div class="userRoleGrid">${Object.entries(roleNames).map(([value,label])=>`<label class="userRoleCard"><input type="radio" name="accountType" value="${value}" ${selected===value?"checked":""}><span><b>${label}</b><small>${roleDetails[value]}</small></span></label>`).join("")}</div>`}
async function userDialog(kind="FIELD",existing=null){const selected=kind==="FIELD"?"FIELD":existing?.role||"SUPERVISOR";const result=await OfficeSwal.fire({title:existing?"แก้ไขผู้ใช้":"สร้างผู้ใช้งาน",width:620,officeKind:"form",html:`<div class="userEditor"><section><div class="userEditorLabel">ประเภทผู้ใช้</div>${roleCards(selected)}</section><section class="userEditorFields"><label class="fieldOnly"><span>รหัสพนักงาน *</span><input id="swEmployee" value="${esc(existing?.employee_code||"")}" ${existing&&kind==="FIELD"?"readonly":""} placeholder="เช่น 0111"></label><label><span>ชื่อ-สกุล *</span><input id="swFullName" value="${esc(existing?.full_name||"")}" placeholder="ชื่อผู้ใช้งาน"></label><label><span>ชื่อเข้าระบบ *</span><input id="swUsername" value="${esc(existing?.username||existing?.employee_code||"")}" placeholder="อย่างน้อย 4 ตัว"></label>${existing?"":'<label><span>รหัสผ่านชั่วคราว *</span><input id="swPassword" type="password" placeholder="อย่างน้อย 6 ตัว โดยมีตัวอักษรและตัวเลข"></label>'}</section><label class="officeSwitch"><input id="swActive" type="checkbox" ${existing?.active===0?"":"checked"}><span class="officeSwitchTrack"></span><span><b>เปิดใช้งานบัญชี</b><small>ปิดสวิตช์เพื่อระงับการเข้าสู่ระบบ</small></span></label></div>`,showCancelButton:true,confirmButtonText:"บันทึกผู้ใช้",cancelButtonText:"ยกเลิก",focusConfirm:false,didOpen:()=>{const sync=()=>document.querySelector(".fieldOnly").hidden=document.querySelector('input[name="accountType"]:checked')?.value!=="FIELD";document.querySelectorAll('input[name="accountType"]').forEach(x=>x.onchange=sync);if(existing)document.querySelectorAll('input[name="accountType"]').forEach(x=>x.disabled=(kind==="FIELD")!==(x.value==="FIELD"));sync()},preConfirm:()=>{const role=document.querySelector('input[name="accountType"]:checked')?.value||"FIELD",employeeCode=$("swEmployee")?.value.trim()||"",fullName=$("swFullName").value.trim(),username=$("swUsername").value.trim(),password=$("swPassword")?.value||"",active=$("swActive").checked;if(!fullName||!username||(role==="FIELD"&&!employeeCode)){Swal.showValidationMessage("กรุณากรอกข้อมูลที่จำเป็นให้ครบ");return false}if(!existing&&!validPassword(password)){Swal.showValidationMessage("รหัสผ่านชั่วคราวต้องมีอย่างน้อย 6 ตัว โดยมีตัวอักษรและตัวเลข");return false}return{role,employeeCode,fullName,username,password,active}}});return result.isConfirmed?result.value:null}
async function addUser(){const v=await userDialog(view);if(!v)return;try{if(v.role==="FIELD")await AdminAuth.json("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(v)});else await AdminAuth.json("/api/admin/staff-users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(v)});view=v.role==="FIELD"?"FIELD":"OFFICE";syncTabs();await SwalSmall.ok("เพิ่มผู้ใช้แล้ว",v.fullName);await load()}catch(e){SwalSmall.error("เพิ่มผู้ใช้ไม่สำเร็จ",translate(e.message))}}
async function openEditor(kind,id){const u=kind==="FIELD"?fieldUsers.find(x=>x.employee_code===id):officeUsers.find(x=>x.id===Number(id));if(!u)return;const v=await userDialog(kind,u);if(!v)return;try{if(kind==="FIELD")await AdminAuth.json("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(v)});else await AdminAuth.json("/api/admin/staff-users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...v,id:u.id})});await SwalSmall.ok("บันทึกข้อมูลแล้ว",v.fullName);await load()}catch(e){SwalSmall.error("บันทึกไม่สำเร็จ",translate(e.message))}}
async function resetPassword(kind,id){const r=await OfficeSwal.fire({title:"ตั้งรหัสผ่านชั่วคราว",input:"password",inputLabel:"รหัสผ่านใหม่",inputPlaceholder:"อย่างน้อย 6 ตัว โดยมีตัวอักษรและตัวเลข",showCancelButton:true,confirmButtonText:"ตั้งรหัสใหม่",cancelButtonText:"ยกเลิก",officeKind:"form",inputValidator:v=>!validPassword(v)?"กรุณากรอกอย่างน้อย 6 ตัว โดยมีตัวอักษรและตัวเลข":undefined});if(!r.isConfirmed)return;try{const url=kind==="FIELD"?`/api/users/${encodeURIComponent(id)}/reset-password`:`/api/admin/staff-users/${id}/reset-password`;await AdminAuth.json(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:r.value})});await SwalSmall.ok("ตั้งรหัสใหม่แล้ว","ผู้ใช้ต้องเข้าสู่ระบบด้วยรหัสใหม่")}catch(e){SwalSmall.error("ตั้งรหัสไม่สำเร็จ",translate(e.message))}}
async function disableUser(kind,id){const u=kind==="FIELD"?fieldUsers.find(x=>x.employee_code===id):officeUsers.find(x=>x.id===Number(id));const r=await OfficeSwal.fire({title:"ระงับบัญชีผู้ใช้",html:`<div class="officeDialogIntro officeDialogIntro--danger"><span>!</span><div><strong>${esc(u?.full_name||"")}</strong><p>ผู้ใช้นี้จะไม่สามารถเข้าสู่ระบบได้</p></div></div>`,showCancelButton:true,confirmButtonText:"ระงับบัญชี",cancelButtonText:"ยกเลิก",officeKind:"danger"});if(!r.isConfirmed)return;try{const url=kind==="FIELD"?`/api/users/${encodeURIComponent(id)}`:`/api/admin/staff-users/${id}`;await AdminAuth.json(url,{method:"DELETE"});await load()}catch(e){SwalSmall.error("ระงับบัญชีไม่สำเร็จ",translate(e.message))}}
async function deleteUser(kind,id){const u=kind==="FIELD"?fieldUsers.find(x=>x.employee_code===id):officeUsers.find(x=>x.id===Number(id));const r=await OfficeSwal.fire({title:"ลบบัญชีผู้ใช้งานถาวร",html:`<div class="officeDialogIntro officeDialogIntro--danger"><span>!</span><div><strong>${esc(u?.full_name||"")}</strong><p>ลบบัญชีที่ไม่มีประวัติงานเท่านั้น และไม่สามารถย้อนกลับได้</p></div></div><div class="officeDialogForm"><label><span>พิมพ์คำว่า ลบ เพื่อยืนยัน</span><input id="confirmDeleteUser" autocomplete="off"></label></div>`,showCancelButton:true,confirmButtonText:"ลบบัญชีถาวร",cancelButtonText:"ยกเลิก",officeKind:"danger",focusConfirm:false,preConfirm:()=>{if($("confirmDeleteUser").value.trim()!=="ลบ"){Swal.showValidationMessage("กรุณาพิมพ์คำว่า ลบ");return false}return true}});if(!r.isConfirmed)return;try{const url=kind==="FIELD"?`/api/users/${encodeURIComponent(id)}/delete`:`/api/admin/staff-users/${id}/delete`;await AdminAuth.json(url,{method:"POST"});await SwalSmall.ok("ลบบัญชีแล้ว",u?.full_name||"");await load()}catch(e){SwalSmall.error("ลบบัญชีไม่สำเร็จ",translate(e.message))}}
async function recoveryCodes(){const r=await SwalSmall.confirm("สร้างรหัสกู้คืนชุดใหม่?","รหัสชุดเดิมที่ยังไม่ได้ใช้จะถูกยกเลิก");if(!r.isConfirmed)return;try{const d=await AdminAuth.json("/api/admin/recovery-codes",{method:"POST"});await OfficeSwal.fire({title:"รหัสกู้คืนฉุกเฉิน",width:560,officeKind:"form",html:`<div class="recoveryNotice">บันทึกหรือพิมพ์เก็บไว้ในที่ปลอดภัย รหัสแต่ละชุดใช้ได้ครั้งเดียวและจะไม่แสดงอีก</div><div class="recoveryCodeGrid">${d.codes.map(x=>`<code>${esc(x)}</code>`).join("")}</div>`,confirmButtonText:"บันทึกเรียบร้อย"})}catch(e){SwalSmall.error("สร้างรหัสกู้คืนไม่สำเร็จ",translate(e.message))}}
function syncTabs(){document.querySelectorAll(".userTypeTabButtons button[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));render()}
function translate(v){return({USERNAME_ALREADY_USED:"ชื่อเข้าระบบนี้มีผู้ใช้อยู่แล้ว",PASSWORD_REQUIRED_FOR_NEW_USER:"กรุณากำหนดรหัสผ่านชั่วคราว",USER_FIELDS_REQUIRED:"กรุณากรอกข้อมูลที่จำเป็นให้ครบ",PASSWORD_TOO_SHORT:"รหัสผ่านต้องมีอย่างน้อย 6 ตัว โดยมีตัวอักษรและตัวเลข",LAST_ADMIN_PROTECTED:"ไม่สามารถระงับ ลบ หรือลดสิทธิ์ผู้ดูแลระบบคนสุดท้ายได้",CANNOT_DELETE_CURRENT_USER:"ไม่สามารถลบบัญชีที่กำลังใช้งานอยู่",USER_HAS_WORK_HISTORY:"บัญชีนี้มีแผนงานหรือประวัติการทำงานแล้ว กรุณาใช้การระงับแทน"})[v]||v}
$("addUserBtn").onclick=addUser;$("recoveryCodesBtn").onclick=recoveryCodes;$("userSearch").oninput=render;document.querySelectorAll(".userTypeTabButtons button[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;syncTabs()});await load();
})();
