(async()=>{
if(!await AdminAuth.guard())return;
const $=id=>document.getElementById(id); let users=[],brands=[],items=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function showTab(name){[["import","Import"],["manage","Manage"],["review","Review"]].forEach(([k,n])=>{$("tab"+n).classList.toggle("active",k===name);$(k+"Area").classList.toggle("hidden",k!==name)});if(name==="manage")loadItems();if(name==="review")loadReviews()}
$("tabImport").onclick=()=>showTab("import");$("tabManage").onclick=()=>showTab("manage");$("tabReview").onclick=()=>showTab("review");
async function base(){const [u,b]=await Promise.all([AdminAuth.json("/api/users"),AdminAuth.json("/api/brands")]);users=(u.items||[]).filter(x=>x.active);brands=(b.items||[]).filter(x=>x.active);$("manageUser").innerHTML=users.map(x=>`<option value="${esc(x.employee_code)}">${esc(x.employee_code)} — ${esc(x.full_name)}</option>`).join("")}
async function loadItems(){const user=$("manageUser").value;if(!user)return;const q=new URLSearchParams({employeeCode:user,from:$("manageFrom").value,to:$("manageTo").value});const d=await AdminAuth.json("/api/admin/work-plan-items?"+q);items=d.items||[];$("manageSummary").textContent=`${items.length} งาน`;$("manageRows").innerHTML=items.map(x=>`<tr><td>${esc(x.work_date)}</td><td>${esc(x.brand)}</td><td>${esc(x.store_code)}</td><td>${esc(x.store_name)}</td><td>${esc(x.pos_count)}</td><td><button class="ghost editPlan" data-id="${x.id}">แก้ไข</button> <button class="ghost dangerBtn delPlan" data-id="${x.id}">ลบ</button></td></tr>`).join("");document.querySelectorAll('.editPlan').forEach(b=>b.onclick=()=>editItem(Number(b.dataset.id)));document.querySelectorAll('.delPlan').forEach(b=>b.onclick=()=>deleteItem(Number(b.dataset.id)))}
$("loadPlanItemsBtn").onclick=loadItems;$("manageUser").onchange=loadItems;
async function itemDialog(x=null){const r=await Swal.fire({title:x?"แก้ไขแผนงาน":"เพิ่มแผนงาน",customClass:{popup:"swal-compact"},html:`<div class="swalForm"><label>วันที่<input id="pDate" type="date" class="swal2-input" value="${esc(x?.work_date||'')}"></label><label>แบรนด์<select id="pBrand" class="swal2-select">${brands.map(b=>`<option ${b.brand_name===x?.brand?'selected':''}>${esc(b.brand_name)}</option>`).join('')}</select></label><label>รหัสร้าน<input id="pCode" class="swal2-input" value="${esc(x?.store_code||'')}"></label><label>ชื่อร้าน<input id="pName" class="swal2-input" value="${esc(x?.store_name||'')}"></label><label>จำนวน POS<input id="pPos" type="number" min="1" max="99" class="swal2-input" value="${x?.pos_count||1}"></label></div>`,showCancelButton:true,confirmButtonText:"บันทึก",cancelButtonText:"ยกเลิก",preConfirm:()=>({workDate:document.getElementById('pDate').value,brand:document.getElementById('pBrand').value,storeCode:document.getElementById('pCode').value.trim(),storeName:document.getElementById('pName').value.trim(),posCount:Number(document.getElementById('pPos').value||1)})});return r.isConfirmed?r.value:null}
async function editItem(id){const x=items.find(i=>i.id===id),v=await itemDialog(x);if(!v)return;await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...v,businessType:x.business_type||'',openClose:x.open_close||'',address:x.address||'',storeFormat:x.store_format||'',rank:x.rank||'',latitude:x.latitude||'',longitude:x.longitude||'',storeNote:x.store_note||''})});await SwalSmall.ok('บันทึกแล้ว');loadItems()}
$("addPlanItemBtn").onclick=async()=>{const v=await itemDialog();if(!v)return;await AdminAuth.json('/api/admin/work-plan-items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...v,employeeCode:$("manageUser").value})});await SwalSmall.ok('เพิ่มงานแล้ว');loadItems()};
async function deleteItem(id){const r=await Swal.fire({title:'ลบงานนี้?',icon:'warning',showCancelButton:true,confirmButtonText:'ลบ',cancelButtonText:'ยกเลิก'});if(!r.isConfirmed)return;await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'DELETE'});loadItems()}
async function loadReviews(){const status=$("reviewStatus").value;const d=await AdminAuth.json('/api/admin/submissions?status='+encodeURIComponent(status));const list=d.items||[];$("reviewList").innerHTML=list.length?list.map(s=>`<article class="reviewCard"><div><strong>${esc(s.full_name)} · ${esc(s.store_name)}</strong><span>${esc(s.work_date)} · ${esc(s.brand)} · ${esc(s.store_code)}</span></div><div class="reviewState">${s.status==='SUBMITTED'?'รอตรวจ':s.status==='RETURNED'?'ส่งกลับแก้ไข':'ผ่านแล้ว'}</div><button class="secondary reviewBtn" data-id="${s.id}">ตรวจ</button></article>`).join(''):'<div class="emptyList">ไม่มีรายการ</div>';document.querySelectorAll('.reviewBtn').forEach(b=>b.onclick=()=>reviewOne(Number(b.dataset.id)))}
$("reviewStatus").onchange=loadReviews;$("refreshReviewBtn").onclick=loadReviews;
async function reviewOne(id){const d=await AdminAuth.json(`/api/admin/submissions/${id}`);const s=d.submission,rows=d.records||[];const html=`<div class="reviewDetail"><div><b>${esc(s.store_name)}</b><br>${esc(s.work_date)} · ${esc(s.store_code)}</div><table><tr><th>POS</th><th>ยอดลูกค้า</th><th>วันที่</th><th>เวลา</th></tr>${rows.map(r=>`<tr><td>${r.pos_number}</td><td>${esc(r.customer_no)}</td><td>${esc(r.bill_date)}</td><td>${esc(r.bill_time)}</td></tr>`).join('')}</table></div>`;const r=await Swal.fire({title:'ตรวจข้อมูล',html,showCancelButton:true,showDenyButton:true,confirmButtonText:'ผ่าน',denyButtonText:'ส่งกลับแก้ไข',cancelButtonText:'ปิด',customClass:{popup:'swal-wide'}});if(r.isConfirmed){await AdminAuth.json(`/api/admin/submissions/${id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'APPROVE'})});loadReviews()}else if(r.isDenied){const rr=await Swal.fire({title:'เหตุผลที่ส่งกลับ',input:'textarea',inputPlaceholder:'ระบุสิ่งที่ต้องแก้ไข',showCancelButton:true,confirmButtonText:'ส่งกลับ',inputValidator:v=>!String(v||'').trim()?'กรุณาระบุเหตุผล':undefined});if(rr.isConfirmed){await AdminAuth.json(`/api/admin/submissions/${id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'RETURN',reason:rr.value})});loadReviews()}}}
await base();
})();
