(async()=>{
if(!await AdminAuth.guard())return;
const $=id=>document.getElementById(id); let users=[],brands=[],items=[],calendarItems=[]; const selected=new Set();
let calendarMonth="",selectedCalendarDate="";
let listRequest=0,calendarRequest=0;
const THAI_MONTHS=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:v||"-"}
function pad(v){return String(v).padStart(2,"0")}
function todayBangkok(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const value=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${value.year}-${value.month}-${value.day}`}
function monthBounds(month){const m=String(month||"").match(/^(\d{4})-(\d{2})$/);if(!m)return null;const year=Number(m[1]),monthNumber=Number(m[2]);const last=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();return{from:`${year}-${pad(monthNumber)}-01`,to:`${year}-${pad(monthNumber)}-${pad(last)}`}}
function ensureManageDates(){if(!$('manageFrom').value&&!$('manageTo').value){calendarMonth=todayBangkok().slice(0,7);const b=monthBounds(calendarMonth);$('manageFrom').value=b.from;$('manageTo').value=b.to}else calendarMonth=($('manageFrom').value||$('manageTo').value||todayBangkok()).slice(0,7)}
function showTab(name){[["import","Import"],["manage","Manage"],["review","Review"]].forEach(([k,n])=>{$("tab"+n).classList.toggle("active",k===name);$(k+"Area").classList.toggle("hidden",k!==name)});if(name==="manage"){ensureManageDates();refreshManageData()}if(name==="review")loadReviews()}
$("tabImport").onclick=()=>showTab("import");$("tabManage").onclick=()=>showTab("manage");$("tabReview").onclick=()=>showTab("review");
async function base(){const [u,b]=await Promise.all([AdminAuth.json("/api/users"),AdminAuth.json("/api/brands")]);users=(u.items||[]).filter(x=>x.active);brands=(b.items||[]).filter(x=>x.active);$("manageUser").innerHTML=users.map(x=>`<option value="${esc(x.employee_code)}">${esc(x.employee_code)} — ${esc(x.full_name)}</option>`).join("")}
function statusLabel(x){if(x.plan_status==="MOVED")return `ย้ายไป ${fmt(x.moved_to_date)}`;if(x.origin_work_date)return `ย้ายมาจาก ${fmt(x.origin_work_date)}`;return "ใช้งาน"}
async function requestItems(user,from,to){if(!user)return[];const q=new URLSearchParams({employeeCode:user,from:from||"",to:to||""});const d=await AdminAuth.json("/api/admin/work-plan-items?"+q);return d.items||[]}
async function loadItems(){const request=++listRequest,user=$("manageUser").value,from=$("manageFrom").value,to=$("manageTo").value,data=await requestItems(user,from,to);if(request!==listRequest||user!==$("manageUser").value)return;items=data;renderGroups()}
async function loadCalendar(){if(!calendarMonth)calendarMonth=todayBangkok().slice(0,7);const request=++calendarRequest,user=$("manageUser").value,month=calendarMonth,b=monthBounds(month),data=b?await requestItems(user,b.from,b.to):[];if(request!==calendarRequest||user!==$("manageUser").value||month!==calendarMonth)return;calendarItems=data;renderCalendar()}
async function refreshManageData(){const user=$("manageUser").value;if(!user){items=[];calendarItems=[];renderGroups();renderCalendar();return}selected.clear();updateSelected();await Promise.all([loadItems(),loadCalendar()])}
function updateManageMetrics(list,term){const active=list.filter(x=>x.plan_status!=="MOVED"),moved=list.length-active.length,days=new Set(active.map(x=>x.work_date)).size,pos=active.reduce((sum,x)=>sum+Number(x.pos_count||0),0),from=$("manageFrom").value,to=$("manageTo").value;$("manageActiveKpi").textContent=active.length;$("manageDaysKpi").textContent=days;$("managePosKpi").textContent=pos;$("manageMovedKpi").textContent=moved;const period=from&&to?(from===to?fmt(from):`${fmt(from)} – ${fmt(to)}`):"ทุกวันที่";$("manageSummary").textContent=`${active.length} รายการ · ${period}${term?` · รหัสร้าน ${term}`:""}`}
function renderGroups(){const host=$("manageDayGroups"),term=$("manageStoreSearch").value.trim().toLowerCase();const visible=term?items.filter(x=>String(x.store_code||"").toLowerCase().includes(term)):items;updateManageMetrics(visible,term);const map=new Map();visible.forEach(x=>{if(!map.has(x.work_date))map.set(x.work_date,[]);map.get(x.work_date).push(x)});host.innerHTML=[...map.entries()].map(([date,list])=>{const active=list.filter(x=>x.plan_status!=="MOVED");return `<section class="dayPlanCard"><header><div><strong>${fmt(date)}</strong><span>${active.length} ร้าน${list.length-active.length?` · ย้ายแล้ว ${list.length-active.length}`:""}</span></div><button class="ghost moveDayBtn" data-date="${date}" ${active.length?"":"disabled"}>ย้ายทั้งวัน</button></header><div class="dayStoreList">${list.map(x=>`<article class="dayStoreRow ${x.plan_status==="MOVED"?"moved":""}">${x.plan_status!=="MOVED"?`<input type="checkbox" class="pickStore" data-id="${x.id}" ${selected.has(x.id)?"checked":""}>`:'<span class="movedDot"></span>'}<div class="dayBrand">${esc(x.brand_abbr||x.brand)}</div><div class="dayStoreMain"><strong>${esc(x.store_name)}</strong><span>${esc(x.store_code)} · ${esc(x.brand)} · ${x.pos_count} POS</span>${x.change_note?`<small>${esc(x.change_note)}</small>`:""}</div><div class="planState ${x.plan_status==="MOVED"?"moved":"active"}">${statusLabel(x)}</div><div class="rowActions">${x.plan_status!=="MOVED"?`<button class="ghost editPlan" data-id="${x.id}">แก้ไข</button><button class="ghost moveOne" data-id="${x.id}">ย้ายวัน</button><button class="ghost dangerBtn delPlan" data-id="${x.id}">ลบ</button>`:""}</div></article>`).join("")}</div></section>`}).join("")||'<div class="emptyList">ไม่พบแผนงานตามวันที่และรหัสร้านที่เลือก</div>';
 document.querySelectorAll('.pickStore').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.id);c.checked?selected.add(id):selected.delete(id);updateSelected()});
 document.querySelectorAll('.editPlan').forEach(b=>b.onclick=()=>editItem(Number(b.dataset.id)));document.querySelectorAll('.moveOne').forEach(b=>b.onclick=()=>moveIds([Number(b.dataset.id)]));document.querySelectorAll('.delPlan').forEach(b=>b.onclick=()=>deleteItem(Number(b.dataset.id)));document.querySelectorAll('.moveDayBtn').forEach(b=>b.onclick=()=>moveDay(b.dataset.date));
}
function renderCalendar(){const host=$("manageCalendarGrid");if(!host)return;const m=String(calendarMonth||"").match(/^(\d{4})-(\d{2})$/);if(!m){host.innerHTML="";return}const year=Number(m[1]),month=Number(m[2]),days=new Date(Date.UTC(year,month,0)).getUTCDate(),offset=new Date(Date.UTC(year,month-1,1)).getUTCDay(),today=todayBangkok();const counts=new Map();calendarItems.filter(x=>x.plan_status!=="MOVED").forEach(x=>{if(!counts.has(x.work_date))counts.set(x.work_date,new Set());counts.get(x.work_date).add(`${x.brand_abbr||x.brand}|${x.store_code}`)});$("calendarMonthLabel").textContent=`${THAI_MONTHS[month-1]} ${year}`;const cells=[];for(let i=0;i<offset;i++)cells.push('<span class="workCalendarBlank" aria-hidden="true"></span>');for(let day=1;day<=days;day++){const date=`${year}-${pad(month)}-${pad(day)}`,count=counts.get(date)?.size||0,classes=["workCalendarDay",count?"hasJobs":"",date===today?"today":"",date===selectedCalendarDate?"selected":""].filter(Boolean).join(" ");cells.push(`<button type="button" class="${classes}" data-date="${date}" aria-label="${fmt(date)}${count?` มี ${count} ร้าน`:" ไม่มีงาน"}"><span>${day}</span>${count?`<strong>${count} ร้าน</strong>`:""}</button>`)}host.innerHTML=cells.join("");host.querySelectorAll(".workCalendarDay").forEach(button=>button.onclick=async()=>{selectedCalendarDate=button.dataset.date;$("manageFrom").value=selectedCalendarDate;$("manageTo").value=selectedCalendarDate;selected.clear();updateSelected();renderCalendar();await loadItems()})}
function updateSelected(){$("moveSelectedBtn").disabled=selected.size===0;$("moveSelectedBtn").textContent=selected.size?`ย้ายร้านที่เลือก (${selected.size})`:"ย้ายร้านที่เลือก"}
function shiftMonth(delta){const [year,month]=calendarMonth.split("-").map(Number),date=new Date(Date.UTC(year,month-1+delta,1));calendarMonth=`${date.getUTCFullYear()}-${pad(date.getUTCMonth()+1)}`;selectedCalendarDate="";const b=monthBounds(calendarMonth);$("manageFrom").value=b.from;$("manageTo").value=b.to;refreshManageData()}
$("loadPlanItemsBtn").onclick=()=>{calendarMonth=($("manageFrom").value||$("manageTo").value||todayBangkok()).slice(0,7);selectedCalendarDate=$("manageFrom").value&&$("manageFrom").value===$("manageTo").value?$("manageFrom").value:"";refreshManageData()};$("manageUser").onchange=()=>{selectedCalendarDate="";refreshManageData()};$("manageStoreSearch").oninput=renderGroups;$("manageStoreSearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();renderGroups()}};$("calendarPrevBtn").onclick=()=>shiftMonth(-1);$("calendarNextBtn").onclick=()=>shiftMonth(1);$("calendarTodayBtn").onclick=()=>{calendarMonth=todayBangkok().slice(0,7);selectedCalendarDate="";const b=monthBounds(calendarMonth);$("manageFrom").value=b.from;$("manageTo").value=b.to;refreshManageData()};$("moveSelectedBtn").onclick=()=>moveIds([...selected]);
async function askMove(title){const r=await Swal.fire({title,customClass:{popup:"swal-compact"},html:`<div class="swalForm"><label>ย้ายไปวันที่<input id="mvDate" type="date" class="swal2-input"></label><label>เหตุผล<textarea id="mvReason" class="swal2-textarea" placeholder="เช่น ผู้ปฏิบัติงานขอเลื่อนวัน"></textarea></label></div>`,showCancelButton:true,confirmButtonText:"ย้ายแผนงาน",cancelButtonText:"ยกเลิก",preConfirm:()=>{const toDate=document.getElementById('mvDate').value,reason=document.getElementById('mvReason').value.trim();if(!toDate||!reason){Swal.showValidationMessage('กรุณาระบุวันที่ใหม่และเหตุผล');return false}return{toDate,reason}}});return r.isConfirmed?r.value:null}
async function moveDay(fromDate){const v=await askMove(`ย้ายงานทั้งหมดวันที่ ${fmt(fromDate)}`);if(!v)return;try{const d=await AdminAuth.json('/api/admin/work-plan-move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeCode:$("manageUser").value,fromDate,toDate:v.toDate,reason:v.reason})});await SwalSmall.ok('ย้ายแผนงานแล้ว',`${d.count} ร้าน`);refreshManageData()}catch(e){showMoveError(e)}}
async function moveIds(ids){if(!ids.length)return;const v=await askMove(`ย้าย ${ids.length} ร้านที่เลือก`);if(!v)return;try{const d=await AdminAuth.json('/api/admin/work-plan-move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeCode:$("manageUser").value,ids,toDate:v.toDate,reason:v.reason})});await SwalSmall.ok('ย้ายแผนงานแล้ว',`${d.count} ร้าน`);refreshManageData()}catch(e){showMoveError(e)}}
function showMoveError(e){const t=String(e.message||e);const map={WORK_ALREADY_SUBMITTED:'มีงานที่ส่งตรวจแล้ว ต้องจัดการงานที่ส่งมาก่อนย้าย',TARGET_DUPLICATE_STORE:'วันที่ปลายทางมีร้านเดียวกันอยู่แล้ว',TARGET_DATE_SAME_AS_SOURCE:'วันที่ใหม่ต้องไม่ใช่วันเดิม',NO_ACTIVE_WORK_TO_MOVE:'ไม่พบงานที่สามารถย้ายได้'};SwalSmall.error('ย้ายแผนงานไม่สำเร็จ',map[t]||t)}
async function itemDialog(x=null){const r=await Swal.fire({title:x?"แก้ไขข้อมูลร้าน":"เพิ่มแผนงาน",customClass:{popup:"swal-compact"},html:`<div class="swalForm"><label>วันที่<input id="pDate" type="date" class="swal2-input" value="${esc(x?.work_date||'')}" ${x?'readonly':''}></label>${x?'<div class="small">หากต้องการเปลี่ยนวัน ให้ใช้ปุ่ม “ย้ายวัน” เพื่อเก็บรายการเดิมไว้เป็นหลักฐาน</div>':''}<label>แบรนด์<select id="pBrand" class="swal2-select">${brands.map(b=>`<option ${b.brand_name===x?.brand?'selected':''}>${esc(b.brand_name)}</option>`).join('')}</select></label><label>รหัสร้าน<input id="pCode" class="swal2-input" value="${esc(x?.store_code||'')}"></label><label>ชื่อร้าน<input id="pName" class="swal2-input" value="${esc(x?.store_name||'')}"></label><label>จำนวน POS<input id="pPos" type="number" min="1" max="99" class="swal2-input" value="${x?.pos_count||1}"></label><label>เหตุผล/หมายเหตุ<textarea id="pReason" class="swal2-textarea" placeholder="ระบุเหตุผลที่แก้ไข">${x?'แก้ไขข้อมูลในวันเดิม':'เพิ่มงานโดย Admin'}</textarea></label></div>`,showCancelButton:true,confirmButtonText:"บันทึก",cancelButtonText:"ยกเลิก",preConfirm:()=>({workDate:document.getElementById('pDate').value,brand:document.getElementById('pBrand').value,storeCode:document.getElementById('pCode').value.trim(),storeName:document.getElementById('pName').value.trim(),posCount:Number(document.getElementById('pPos').value||1),reason:document.getElementById('pReason').value.trim()})});return r.isConfirmed?r.value:null}
async function editItem(id){const x=items.find(i=>i.id===id),v=await itemDialog(x);if(!v)return;await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...v,businessType:x.business_type||'',openClose:x.open_close||'',address:x.address||'',storeFormat:x.store_format||'',rank:x.rank||'',latitude:x.latitude||'',longitude:x.longitude||'',storeNote:x.store_note||''})});await SwalSmall.ok('บันทึกแล้ว');refreshManageData()}
$("addPlanItemBtn").onclick=async()=>{const v=await itemDialog();if(!v)return;await AdminAuth.json('/api/admin/work-plan-items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...v,employeeCode:$("manageUser").value})});await SwalSmall.ok('เพิ่มงานแล้ว');refreshManageData()};
async function deleteItem(id){const x=items.find(i=>i.id===id);const r=await Swal.fire({title:'ลบงานนี้?',text:x?.store_name||'',input:'textarea',inputPlaceholder:'เหตุผลที่ลบ',icon:'warning',showCancelButton:true,confirmButtonText:'ลบ',cancelButtonText:'ยกเลิก',inputValidator:v=>!String(v||'').trim()?'กรุณาระบุเหตุผล':undefined});if(!r.isConfirmed)return;await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({reason:r.value})});refreshManageData()}
$("historyBtn").onclick=async()=>{try{const d=await AdminAuth.json(`/api/admin/work-plan-history?employeeCode=${encodeURIComponent($("manageUser").value)}&limit=150`);const action={IMPORT:'นำเข้า',ADD:'เพิ่ม',EDIT:'แก้ไข',MOVE:'ย้ายวัน',DELETE:'ลบ'};const html=`<div class="historyList">${(d.items||[]).map(x=>`<article><strong>${action[x.action]||x.action}</strong><span>${esc(x.created_at||'')} · ${esc(x.admin_username||'')}</span><div>${x.from_date?fmt(x.from_date):''}${x.to_date&&x.to_date!==x.from_date?` → ${fmt(x.to_date)}`:''}</div><small>${esc(x.reason||'-')}</small></article>`).join('')||'<div class="emptyList">ยังไม่มีประวัติ</div>'}</div>`;await Swal.fire({title:'ประวัติการเปลี่ยนแปลงแผนงาน',html,width:760,confirmButtonText:'ปิด',customClass:{popup:'swal-wide'}})}catch(e){SwalSmall.error('โหลดประวัติไม่สำเร็จ',e.message)}};

// Review workflow
async function loadReviews(){const status=$("reviewStatus").value;const d=await AdminAuth.json('/api/admin/submissions?status='+encodeURIComponent(status));const list=d.items||[];$("reviewList").innerHTML=list.length?list.map(s=>`<article class="reviewCard"><div><strong>${esc(s.full_name)} · ${esc(s.store_name)}</strong><span>${esc(s.work_date)} · ${esc(s.brand)} · ${esc(s.store_code)}</span></div><div class="reviewState">${s.status==='SUBMITTED'?'รอตรวจ':s.status==='RETURNED'?'ส่งกลับแก้ไข':'ผ่านแล้ว'}</div><button class="secondary reviewBtn" data-id="${s.id}">ตรวจ</button></article>`).join(''):'<div class="emptyList">ไม่มีรายการ</div>';document.querySelectorAll('.reviewBtn').forEach(b=>b.onclick=()=>reviewOne(Number(b.dataset.id)))}
$("reviewStatus").onchange=loadReviews;$("refreshReviewBtn").onclick=loadReviews;
async function reviewOne(id){const d=await AdminAuth.json(`/api/admin/submissions/${id}`);const s=d.submission,rows=d.records||[];const html=`<div class="reviewDetail"><div><b>${esc(s.store_name)}</b><br>${esc(s.work_date)} · ${esc(s.store_code)}</div><table><tr><th>POS</th><th>ยอดลูกค้า</th><th>วันที่</th><th>เวลา</th></tr>${rows.map(r=>`<tr><td>${r.pos_number}</td><td>${esc(r.customer_no)}</td><td>${esc(r.bill_date)}</td><td>${esc(r.bill_time)}</td></tr>`).join('')}</table></div>`;const r=await Swal.fire({title:'ตรวจข้อมูล',html,showCancelButton:true,showDenyButton:true,confirmButtonText:'ผ่าน',denyButtonText:'ส่งกลับแก้ไข',cancelButtonText:'ปิด',customClass:{popup:'swal-wide'}});if(r.isConfirmed){await AdminAuth.json(`/api/admin/submissions/${id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'APPROVE'})});loadReviews()}else if(r.isDenied){const rr=await Swal.fire({title:'เหตุผลที่ส่งกลับ',input:'textarea',inputPlaceholder:'ระบุสิ่งที่ต้องแก้ไข',showCancelButton:true,confirmButtonText:'ส่งกลับ',inputValidator:v=>!String(v||'').trim()?'กรุณาระบุเหตุผล':undefined});if(rr.isConfirmed){await AdminAuth.json(`/api/admin/submissions/${id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'RETURN',reason:rr.value})});loadReviews()}}}
await base();
})();
