(async()=>{
if(!await AdminAuth.guard())return;
const $=id=>document.getElementById(id); let users=[],brands=[],items=[],calendarItems=[]; const selected=new Set();
let calendarMonth="",selectedCalendarDate="";
let listRequest=0,calendarRequest=0;
const THAI_MONTHS=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:v||"-"}
function pad(v){return String(v).padStart(2,"0")}
function todayBangkok(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const value=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${value.year}-${value.month}-${value.day}`}
function monthBounds(month){const m=String(month||"").match(/^(\d{4})-(\d{2})$/);if(!m)return null;const year=Number(m[1]),monthNumber=Number(m[2]);const last=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();return{from:`${year}-${pad(monthNumber)}-01`,to:`${year}-${pad(monthNumber)}-${pad(last)}`}}
function ensureManageDates(){if(!$('manageFrom').value&&!$('manageTo').value){calendarMonth=todayBangkok().slice(0,7);const b=monthBounds(calendarMonth);$('manageFrom').value=b.from;$('manageTo').value=b.to}else calendarMonth=($('manageFrom').value||$('manageTo').value||todayBangkok()).slice(0,7)}
function showTab(name){[["import","Import"],["manage","Manage"]].forEach(([k,n])=>{$("tab"+n).classList.toggle("active",k===name);$(k+"Area").classList.toggle("hidden",k!==name)});if(name==="manage"){ensureManageDates();refreshManageData()}}
$("tabImport").onclick=()=>showTab("import");$("tabManage").onclick=()=>showTab("manage");
async function base(){const [u,b]=await Promise.all([AdminAuth.json("/api/users"),AdminAuth.json("/api/brands")]);users=(u.items||[]).filter(x=>x.active);brands=(b.items||[]).filter(x=>x.active);$("manageUser").innerHTML=users.map(x=>`<option value="${esc(x.employee_code)}">${esc(x.employee_code)} — ${esc(x.full_name)}</option>`).join("")}
function statusLabel(x){if(x.plan_status==="MOVED")return `ย้ายไป ${fmt(x.moved_to_date)}`;if(x.origin_work_date)return `ย้ายมาจาก ${fmt(x.origin_work_date)}`;return "ใช้งาน"}
function planBrandVisual(x){const label=esc(x.brand_abbr||x.brand||"-");return x.logo_url?`<div class="dayBrand hasLogo"><img src="${esc(x.logo_url)}" alt="${label}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${label}</span></div>`:`<div class="dayBrand"><span>${label}</span></div>`}
async function requestItems(user,from,to){if(!user)return[];const q=new URLSearchParams({employeeCode:user,from:from||"",to:to||""});const d=await AdminAuth.json("/api/admin/work-plan-items?"+q);return d.items||[]}
async function loadItems(){const request=++listRequest,user=$("manageUser").value,from=$("manageFrom").value,to=$("manageTo").value,data=await requestItems(user,from,to);if(request!==listRequest||user!==$("manageUser").value)return;items=data;renderGroups()}
async function loadCalendar(){if(!calendarMonth)calendarMonth=todayBangkok().slice(0,7);const request=++calendarRequest,user=$("manageUser").value,month=calendarMonth,b=monthBounds(month),data=b?await requestItems(user,b.from,b.to):[];if(request!==calendarRequest||user!==$("manageUser").value||month!==calendarMonth)return;calendarItems=data;renderCalendar()}
async function refreshManageData(){const user=$("manageUser").value;if(!user){items=[];calendarItems=[];renderGroups();renderCalendar();return}selected.clear();updateSelected();await Promise.all([loadItems(),loadCalendar()])}
function updateManageMetrics(list,term){const active=list.filter(x=>x.plan_status!=="MOVED"),moved=list.length-active.length,days=new Set(active.map(x=>x.work_date)).size,pos=active.reduce((sum,x)=>sum+Number(x.pos_count||0),0),from=$("manageFrom").value,to=$("manageTo").value;$("manageActiveKpi").textContent=active.length;$("manageDaysKpi").textContent=days;$("managePosKpi").textContent=pos;$("manageMovedKpi").textContent=moved;const period=from&&to?(from===to?fmt(from):`${fmt(from)} – ${fmt(to)}`):"ทุกวันที่";$("manageSummary").textContent=`${active.length} รายการ · ${period}${term?` · รหัสร้าน ${term}`:""}`}
function renderGroups(){const host=$("manageDayGroups"),term=$("manageStoreSearch").value.trim().toLowerCase();const visible=term?items.filter(x=>String(x.store_code||"").toLowerCase().includes(term)):items;updateManageMetrics(visible,term);const map=new Map();visible.forEach(x=>{if(!map.has(x.work_date))map.set(x.work_date,[]);map.get(x.work_date).push(x)});host.innerHTML=[...map.entries()].map(([date,list])=>{const active=list.filter(x=>x.plan_status!=="MOVED");return `<section class="dayPlanCard"><header><div><strong>${fmt(date)}</strong><span>${active.length} ร้าน${list.length-active.length?` · ย้ายแล้ว ${list.length-active.length}`:""}</span></div><button class="ghost moveDayBtn" data-date="${date}" ${active.length?"":"disabled"}>ย้ายทั้งวัน</button></header><div class="dayStoreList">${list.map(x=>`<article class="dayStoreRow ${x.plan_status==="MOVED"?"moved":""}">${x.plan_status!=="MOVED"?`<input type="checkbox" class="pickStore" data-id="${x.id}" ${selected.has(x.id)?"checked":""}>`:'<span class="movedDot"></span>'}${planBrandVisual(x)}<div class="dayStoreMain"><strong>${esc(x.store_name)}</strong><span>${esc(x.store_code)} · ${esc(x.brand)} · ${x.pos_count} POS</span>${x.change_note?`<small>${esc(x.change_note)}</small>`:""}</div><div class="planState ${x.plan_status==="MOVED"?"moved":"active"}">${statusLabel(x)}</div><div class="rowActions">${x.plan_status!=="MOVED"?`<button class="ghost editPlan" data-id="${x.id}">แก้ไข</button><button class="ghost moveOne" data-id="${x.id}">ย้ายวัน</button><button class="ghost dangerBtn delPlan" data-id="${x.id}">ลบ</button>`:""}</div></article>`).join("")}</div></section>`}).join("")||'<div class="emptyList">ไม่พบแผนงานตามวันที่และรหัสร้านที่เลือก</div>';
 document.querySelectorAll('.pickStore').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.id);c.checked?selected.add(id):selected.delete(id);updateSelected()});
 document.querySelectorAll('.editPlan').forEach(b=>b.onclick=()=>editItem(Number(b.dataset.id)));document.querySelectorAll('.moveOne').forEach(b=>b.onclick=()=>moveIds([Number(b.dataset.id)]));document.querySelectorAll('.delPlan').forEach(b=>b.onclick=()=>deleteItem(Number(b.dataset.id)));document.querySelectorAll('.moveDayBtn').forEach(b=>b.onclick=()=>moveDay(b.dataset.date));
}
function renderCalendar(){const host=$("manageCalendarGrid");if(!host)return;const m=String(calendarMonth||"").match(/^(\d{4})-(\d{2})$/);if(!m){host.innerHTML="";return}const year=Number(m[1]),month=Number(m[2]),days=new Date(Date.UTC(year,month,0)).getUTCDate(),offset=new Date(Date.UTC(year,month-1,1)).getUTCDay(),today=todayBangkok();const counts=new Map();calendarItems.filter(x=>x.plan_status!=="MOVED").forEach(x=>{if(!counts.has(x.work_date))counts.set(x.work_date,new Set());counts.get(x.work_date).add(`${x.brand_abbr||x.brand}|${x.store_code}`)});$("calendarMonthLabel").textContent=`${THAI_MONTHS[month-1]} ${year}`;const cells=[];for(let i=0;i<offset;i++)cells.push('<span class="workCalendarBlank" aria-hidden="true"></span>');for(let day=1;day<=days;day++){const date=`${year}-${pad(month)}-${pad(day)}`,count=counts.get(date)?.size||0,classes=["workCalendarDay",count?"hasJobs":"",date===today?"today":"",date===selectedCalendarDate?"selected":""].filter(Boolean).join(" ");cells.push(`<button type="button" class="${classes}" data-date="${date}" aria-label="${fmt(date)}${count?` มี ${count} ร้าน`:" ไม่มีงาน"}"><span>${day}</span>${count?`<strong>${count} ร้าน</strong>`:""}</button>`)}host.innerHTML=cells.join("");host.querySelectorAll(".workCalendarDay").forEach(button=>button.onclick=async()=>{selectedCalendarDate=button.dataset.date;$("manageFrom").value=selectedCalendarDate;$("manageTo").value=selectedCalendarDate;selected.clear();updateSelected();renderCalendar();await loadItems()})}
function updateSelected(){$("moveSelectedBtn").disabled=selected.size===0;$("moveSelectedBtn").textContent=selected.size?`ย้ายร้านที่เลือก (${selected.size})`:"ย้ายร้านที่เลือก"}
function shiftMonth(delta){const [year,month]=calendarMonth.split("-").map(Number),date=new Date(Date.UTC(year,month-1+delta,1));calendarMonth=`${date.getUTCFullYear()}-${pad(date.getUTCMonth()+1)}`;selectedCalendarDate="";const b=monthBounds(calendarMonth);$("manageFrom").value=b.from;$("manageTo").value=b.to;refreshManageData()}
$("loadPlanItemsBtn").onclick=()=>{calendarMonth=($("manageFrom").value||$("manageTo").value||todayBangkok()).slice(0,7);selectedCalendarDate=$("manageFrom").value&&$("manageFrom").value===$("manageTo").value?$("manageFrom").value:"";refreshManageData()};$("manageUser").onchange=()=>{selectedCalendarDate="";refreshManageData()};$("manageStoreSearch").oninput=renderGroups;$("manageStoreSearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();renderGroups()}};$("calendarPrevBtn").onclick=()=>shiftMonth(-1);$("calendarNextBtn").onclick=()=>shiftMonth(1);$("calendarTodayBtn").onclick=()=>{calendarMonth=todayBangkok().slice(0,7);selectedCalendarDate="";const b=monthBounds(calendarMonth);$("manageFrom").value=b.from;$("manageTo").value=b.to;refreshManageData()};$("moveSelectedBtn").onclick=()=>moveIds([...selected]);
async function askMove(title){const r=await Swal.fire({title,customClass:{popup:"swal-compact"},html:`<div class="swalForm"><label>ย้ายไปวันที่<input id="mvDate" type="date" class="swal2-input"></label><label>เหตุผล<textarea id="mvReason" class="swal2-textarea" placeholder="เช่น ผู้ปฏิบัติงานขอเลื่อนวัน"></textarea></label></div>`,showCancelButton:true,confirmButtonText:"ย้ายแผนงาน",cancelButtonText:"ยกเลิก",preConfirm:()=>{const toDate=document.getElementById('mvDate').value,reason=document.getElementById('mvReason').value.trim();if(!toDate||!reason){Swal.showValidationMessage('กรุณาระบุวันที่ใหม่และเหตุผล');return false}return{toDate,reason}}});return r.isConfirmed?r.value:null}
async function moveDay(fromDate){const v=await askMove(`ย้ายงานทั้งหมดวันที่ ${fmt(fromDate)}`);if(!v)return;try{const d=await AdminAuth.json('/api/admin/work-plan-move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeCode:$("manageUser").value,fromDate,toDate:v.toDate,reason:v.reason})});await SwalSmall.ok('ย้ายแผนงานแล้ว',`${d.count} ร้าน`);refreshManageData()}catch(e){showMoveError(e)}}
async function moveIds(ids){if(!ids.length)return;const v=await askMove(`ย้าย ${ids.length} ร้านที่เลือก`);if(!v)return;try{const d=await AdminAuth.json('/api/admin/work-plan-move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeCode:$("manageUser").value,ids,toDate:v.toDate,reason:v.reason})});await SwalSmall.ok('ย้ายแผนงานแล้ว',`${d.count} ร้าน`);refreshManageData()}catch(e){showMoveError(e)}}
function showMoveError(e){const t=String(e.message||e);const map={WORK_ALREADY_SUBMITTED:'มีงานที่ส่งตรวจแล้ว ต้องจัดการงานที่ส่งมาก่อนย้าย',TARGET_DUPLICATE_STORE:'วันที่ปลายทางมีร้านเดียวกันอยู่แล้ว',TARGET_DATE_SAME_AS_SOURCE:'วันที่ใหม่ต้องไม่ใช่วันเดิม',NO_ACTIVE_WORK_TO_MOVE:'ไม่พบงานที่สามารถย้ายได้'};SwalSmall.error('ย้ายแผนงานไม่สำเร็จ',map[t]||t)}
async function itemDialog(x=null){const val=k=>esc(x?.[k]||'');const r=await Swal.fire({title:x?"แก้ไขข้อมูลร้าน":"เพิ่มแผนงาน",width:760,customClass:{popup:"swal-compact swal-wide"},html:`<div class="swalForm planDetailForm"><label>วันที่<input id="pDate" type="date" class="swal2-input" value="${val('work_date')}" ${x?'readonly':''}></label>${x?'<div class="small">หากต้องการเปลี่ยนวัน ให้ใช้ปุ่ม “ย้ายวัน” เพื่อเก็บรายการเดิมไว้เป็นหลักฐาน</div>':''}<label>แบรนด์<select id="pBrand" class="swal2-select">${brands.map(b=>`<option ${b.brand_name===x?.brand?'selected':''}>${esc(b.brand_name)}</option>`).join('')}</select></label><label>รหัสร้าน<input id="pCode" class="swal2-input" value="${val('store_code')}"></label><label>ชื่อร้าน<input id="pName" class="swal2-input" value="${val('store_name')}"></label><label>จำนวน POS<input id="pPos" type="number" min="1" max="99" class="swal2-input" value="${x?.pos_count||1}"></label><label>ประเภทร้าน<input id="pBusinessType" class="swal2-input" value="${val('business_type')}"></label><label>เวลาเปิด-ปิด<input id="pOpenClose" class="swal2-input" value="${val('open_close')}"></label><label class="wideField">ที่อยู่ร้าน<textarea id="pAddress" class="swal2-textarea">${val('address')}</textarea></label><label>รูปแบบร้าน<input id="pStoreFormat" class="swal2-input" value="${val('store_format')}"></label><label>ระดับร้าน<input id="pRank" class="swal2-input" value="${val('rank')}"></label><label>ละติจูด<input id="pLatitude" class="swal2-input" value="${val('latitude')}"></label><label>ลองจิจูด<input id="pLongitude" class="swal2-input" value="${val('longitude')}"></label><label class="wideField">ข้อมูลจากแผนงาน<textarea id="pStoreNote" class="swal2-textarea">${val('store_note')}</textarea></label><label class="wideField">เหตุผลที่เปลี่ยนแปลง<textarea id="pReason" class="swal2-textarea" placeholder="ระบุเหตุผลที่แก้ไข">${x?'แก้ไขข้อมูลในวันเดิม':'เพิ่มงานโดย Admin'}</textarea></label></div>`,showCancelButton:true,confirmButtonText:"บันทึก",cancelButtonText:"ยกเลิก",preConfirm:()=>{const read=id=>document.getElementById(id).value.trim(),workDate=read('pDate'),storeCode=read('pCode'),storeName=read('pName'),posCount=Number(read('pPos')||1),latitude=read('pLatitude'),longitude=read('pLongitude'),reason=read('pReason');if(!workDate||!storeCode||!storeName||!reason){Swal.showValidationMessage('กรุณากรอกวันที่ รหัสร้าน ชื่อร้าน และเหตุผล');return false}if(!Number.isInteger(posCount)||posCount<1||posCount>99){Swal.showValidationMessage('จำนวน POS ต้องเป็นเลข 1–99');return false}if((latitude&&!longitude)||(!latitude&&longitude)){Swal.showValidationMessage('พิกัดต้องมีทั้งละติจูดและลองจิจูด');return false}return{workDate,brand:read('pBrand'),storeCode,storeName,posCount,businessType:read('pBusinessType'),openClose:read('pOpenClose'),address:read('pAddress'),storeFormat:read('pStoreFormat'),rank:read('pRank'),latitude,longitude,storeNote:read('pStoreNote'),reason}}});return r.isConfirmed?r.value:null}
async function editStoreDialog(x){
 const val=k=>esc(x?.[k]||''),month=`${THAI_MONTHS[Number(x.work_date.slice(5,7))-1]} ${x.work_date.slice(0,4)}`,badge=esc(x.brand_abbr||x.brand||'-'),badgeVisual=x.logo_url?`<img src="${esc(x.logo_url)}" alt="${badge}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${badge}</span>`:badge;
 const scopeBlock=`<div class="receiptScope" role="radiogroup" aria-label="ขอบเขตการแก้ไข">
  <div class="receiptSectionLabel"><span>ขอบเขตการแก้ไข</span><small>เลือกให้ตรงกับผลที่ต้องการ</small></div>
  <div class="receiptScopeGrid">
   <label><input type="radio" name="pScope" value="DAY" checked><span class="receiptScopeIcon">1</span><span><b>เฉพาะวันนี้</b><small>${esc(fmt(x.work_date))}</small></span></label>
   <label title="เฉพาะผู้ใช้งานคนนี้ และเฉพาะเดือนนี้"><input type="radio" name="pScope" value="MONTH"><span class="receiptScopeIcon">30</span><span><b>ทั้งเดือน</b><small>${esc(month)}</small></span></label>
   <label title="ร้านนี้ทุกผู้ใช้งาน และใช้กับไฟล์ที่นำเข้าครั้งต่อไป"><input type="radio" name="pScope" value="PERMANENT"><span class="receiptScopeIcon">&#8734;</span><span><b>ถาวร</b><small>ทุกผู้ใช้และไฟล์ใหม่</small></span></label>
  </div>
 </div>`;
 const r=await Swal.fire({
  title:"แก้ไขข้อมูลร้าน",width:720,padding:0,heightAuto:false,focusConfirm:false,buttonsStyling:false,
  customClass:{popup:"receiptStoreModal",title:"receiptModalTitle",htmlContainer:"receiptModalBody",actions:"receiptModalActions",confirmButton:"receiptSaveButton",cancelButton:"receiptCancelButton",validationMessage:"receiptValidation"},
  html:`<div class="receiptStoreEditor">
   <div class="receiptStoreSummary"><div class="receiptBrandBadge ${x.logo_url?'hasLogo':''}">${badgeVisual}</div><div><strong>${val('store_name')}</strong><span>${val('store_code')} · ${val('brand')} · ${x.pos_count||1} POS</span></div><time>${esc(fmt(x.work_date))}</time></div>
   ${scopeBlock}
   <input id="pDate" type="hidden" value="${val('work_date')}"><input id="pBrand" type="hidden" value="${val('brand')}"><input id="pCode" type="hidden" value="${val('store_code')}">
   <div class="receiptSectionLabel"><span>ข้อมูลที่ใช้ในแผนงาน</span><small>ข้อมูลหลักที่แสดงใน APK</small></div>
   <div class="receiptPrimaryGrid">
    <label class="receiptField"><span>ชื่อร้าน</span><input id="pName" value="${val('store_name')}" autocomplete="off"></label>
    <label class="receiptField"><span>จำนวน POS</span><input id="pPos" type="number" min="1" max="99" value="${x.pos_count||1}"></label>
    <label class="receiptField"><span>ประเภทร้าน</span><input id="pBusinessType" value="${val('business_type')}" placeholder="เช่น Standalone"></label>
    <label class="receiptField"><span>เวลาเปิด-ปิด</span><input id="pOpenClose" value="${val('open_close')}" placeholder="เช่น 06:00–23:00"></label>
   </div>
   <details class="receiptAdvanced">
    <summary><span><b>รายละเอียดร้านเพิ่มเติม</b><small>ที่อยู่ รูปแบบร้าน ระดับร้าน และพิกัด</small></span><i aria-hidden="true"></i></summary>
    <div class="receiptAdvancedGrid">
     <label class="receiptField receiptFieldFull"><span>ที่อยู่ร้าน</span><textarea id="pAddress" rows="2">${val('address')}</textarea></label>
     <label class="receiptField"><span>รูปแบบร้าน</span><input id="pStoreFormat" value="${val('store_format')}"></label>
     <label class="receiptField"><span>ระดับร้าน</span><input id="pRank" value="${val('rank')}"></label>
     <label class="receiptField"><span>ละติจูด</span><input id="pLatitude" inputmode="decimal" value="${val('latitude')}"></label>
     <label class="receiptField"><span>ลองจิจูด</span><input id="pLongitude" inputmode="decimal" value="${val('longitude')}"></label>
     <label class="receiptField receiptFieldFull"><span>ข้อมูลจากแผนงาน</span><textarea id="pStoreNote" rows="2">${val('store_note')}</textarea></label>
    </div>
   </details>
   <label class="receiptField receiptReason"><span>เหตุผลที่เปลี่ยนแปลง <b>*</b></span><textarea id="pReason" rows="2" placeholder="ระบุเหตุผลเพื่อบันทึกในประวัติ"></textarea></label>
  </div>`,
  showCancelButton:true,confirmButtonText:"บันทึกการเปลี่ยนแปลง",cancelButtonText:"ยกเลิก",
  showClass:{popup:"receiptModalShow"},hideClass:{popup:"receiptModalHide"},
  preConfirm:()=>{const read=id=>document.getElementById(id).value.trim(),storeName=read('pName'),posCount=Number(read('pPos')||1),latitude=read('pLatitude'),longitude=read('pLongitude'),reason=read('pReason'),scope=document.querySelector('input[name="pScope"]:checked')?.value||'DAY';if(!storeName||!reason){Swal.showValidationMessage('กรุณากรอกชื่อร้านและเหตุผล');return false}if(!Number.isInteger(posCount)||posCount<1||posCount>99){Swal.showValidationMessage('จำนวน POS ต้องเป็นเลข 1–99');return false}if((latitude&&!longitude)||(!latitude&&longitude)){Swal.showValidationMessage('พิกัดต้องมีทั้งละติจูดและลองจิจูด');return false}return{scope,workDate:read('pDate'),brand:read('pBrand'),storeCode:read('pCode'),storeName,posCount,businessType:read('pBusinessType'),openClose:read('pOpenClose'),address:read('pAddress'),storeFormat:read('pStoreFormat'),rank:read('pRank'),latitude,longitude,storeNote:read('pStoreNote'),reason}}
 });
 return r.isConfirmed?r.value:null
}
async function editItem(id){const x=items.find(i=>i.id===id),v=await editStoreDialog(x);if(!v)return;const d=await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(v)});const title=d.scope==='PERMANENT'?'บันทึกข้อมูลถาวรแล้ว':d.scope==='MONTH'?'แก้ไขร้านทั้งเดือนแล้ว':'แก้ไขรายการแล้ว';await SwalSmall.ok(title,`${d.affected||1} รายการ`);refreshManageData()}
$("addPlanItemBtn").onclick=async()=>{const v=await itemDialog();if(!v)return;await AdminAuth.json('/api/admin/work-plan-items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...v,employeeCode:$("manageUser").value})});await SwalSmall.ok('เพิ่มงานแล้ว');refreshManageData()};
async function deleteItem(id){const x=items.find(i=>i.id===id);const r=await Swal.fire({title:'ลบงานนี้?',text:x?.store_name||'',input:'textarea',inputPlaceholder:'เหตุผลที่ลบ',icon:'warning',showCancelButton:true,confirmButtonText:'ลบ',cancelButtonText:'ยกเลิก',inputValidator:v=>!String(v||'').trim()?'กรุณาระบุเหตุผล':undefined});if(!r.isConfirmed)return;await AdminAuth.json(`/api/admin/work-plan-items/${id}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({reason:r.value})});refreshManageData()}
$("clearPlansBtn").onclick=async()=>{const employeeCode=$("manageUser").value;if(!employeeCode)return SwalSmall.error("กรุณาเลือกผู้ใช้งาน");const from=$("manageFrom").value,to=$("manageTo").value;const result=await Swal.fire({title:"ล้างแผนงานของผู้ใช้งาน",icon:"warning",html:`<div class="clearPlanForm"><p>งานจะหายจาก APK แต่ประวัติการเปลี่ยนแปลงและงานที่เคยส่งแล้วยังคงอยู่</p><label>ขอบเขต<select id="clearScope" class="swal2-select"><option value="ALL">ทุกวันที่ของผู้ใช้งานนี้</option><option value="RANGE">เฉพาะ ${esc(fmt(from))} ถึง ${esc(fmt(to))}</option></select></label><label>เหตุผล<textarea id="clearReason" class="swal2-textarea" placeholder="เช่น ล้างข้อมูลเพื่ออัปโหลดไฟล์ที่แก้ไขใหม่"></textarea></label><label>พิมพ์รหัส <b>${esc(employeeCode)}</b> เพื่อยืนยัน<input id="clearConfirmation" class="swal2-input" autocomplete="off"></label></div>`,showCancelButton:true,confirmButtonText:"ล้างแผนงาน",cancelButtonText:"ยกเลิก",confirmButtonColor:"#b42318",preConfirm:()=>{const scope=document.getElementById("clearScope").value,reason=document.getElementById("clearReason").value.trim(),confirmation=document.getElementById("clearConfirmation").value.trim();if(!reason){Swal.showValidationMessage("กรุณาระบุเหตุผล");return false}if(confirmation!==employeeCode){Swal.showValidationMessage("รหัสยืนยันไม่ตรงกับผู้ใช้งานที่เลือก");return false}if(scope==="RANGE"&&(!from||!to)){Swal.showValidationMessage("กรุณาเลือกช่วงวันที่ก่อน");return false}return{scope,reason,confirmation}}});if(!result.isConfirmed)return;try{const d=await AdminAuth.json("/api/admin/work-plan-clear",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({employeeCode,...result.value,from,to})});await SwalSmall.ok("ล้างแผนงานแล้ว",`${d.count||0} รายการ · ${d.dayCount||0} วัน`);selectedCalendarDate="";await refreshManageData()}catch(e){SwalSmall.error("ล้างแผนงานไม่สำเร็จ",e.message)}};
$("historyBtn").onclick=async()=>{try{const d=await AdminAuth.json(`/api/admin/work-plan-history?employeeCode=${encodeURIComponent($("manageUser").value)}&limit=150`);const action={IMPORT:'นำเข้า',ADD:'เพิ่ม',EDIT:'แก้ไข',MOVE:'ย้ายวัน',DELETE:'ลบ',CLEAR:'ล้างแผนงาน'};const html=`<div class="historyList">${(d.items||[]).map(x=>`<article><strong>${action[x.action]||x.action}</strong><span>${esc(x.created_at||'')} · ${esc(x.admin_username||'')}</span><div>${x.from_date?fmt(x.from_date):''}${x.to_date&&x.to_date!==x.from_date?` → ${fmt(x.to_date)}`:''}</div><small>${esc(x.reason||'-')}</small></article>`).join('')||'<div class="emptyList">ยังไม่มีประวัติ</div>'}</div>`;await Swal.fire({title:'ประวัติการเปลี่ยนแปลงแผนงาน',html,width:760,confirmButtonText:'ปิด',customClass:{popup:'swal-wide'}})}catch(e){SwalSmall.error('โหลดประวัติไม่สำเร็จ',e.message)}};

await base();
})();
